      MODULE DLAMCH_I
      INTERFACE
      REAL(KIND(0.0D0)) FUNCTION DLAMCH (CMACH) 
!     REAL(DOUBLE) FUNCTION DLAMCH (CMACH) 
      USE vast_kind_param, ONLY:  DOUBLE
!jbq ...Generated by Jacek Bieron
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
      CHARACTER, INTENT(IN) :: CMACH 
!-----------------------------------------------
!   L o c a l   P a r a m e t e r s
!-----------------------------------------------
      REAL(DOUBLE), PARAMETER :: ONE = 1.0D+0 
      REAL(DOUBLE), PARAMETER :: ZERO = 0.0D+0 
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
      INTEGER :: BETA, IMAX, IMIN, IT 
      REAL(DOUBLE) :: BASE, EMAX, EMIN, EPS, PREC, RMACH, RMAX, RMIN, RND, &
         SFMIN, SMALL, T 
      LOGICAL :: FIRST, LRND 
      logical::lsame
      END FUNCTION DLAMCH 
      END INTERFACE
      END MODULE

