      MODULE getinf_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:49:50  12/27/06  
      SUBROUTINE getinf 
!VAST.../DEF1/ NELEC(IN)
!VAST.../DEFAULT/ NDEF(IN)
!VAST.../FOPARM/ ICCUT(OUT)
!VAST.../MCPA/ KMAX(IN)
!VAST.../MCPB/ DIAG(OUT), LFORDR(OUT)
!VAST.../ORB2/ NCF(INOUT), NW(IN)
!VAST...Calls: GETYN, CONVRT
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
