      MODULE lodres_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:49:50  12/27/06  
      SUBROUTINE lodres (IERR) 
      INTEGER, INTENT(OUT) :: IERR 
!VAST.../DEF1/ NELEC(IN)
!VAST.../MCPA/ KMAX(IN)
!VAST.../FOPARM/ ICCUT(INOUT)
!VAST.../MCPB/ DIAG(INOUT), LFORDR(INOUT)
!VAST.../ORB2/ NCF(IN), NW(IN)
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
