      MODULE factt_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:26   2/14/04  
      SUBROUTINE factt 
!VAST.../FACTS/ GAM(INOUT)
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
