      MODULE getyn_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:48:16   2/14/04  
      LOGICAL FUNCTION getyn ( ) 
!VAST.../IOUNIT/ ISTDI(IN), ISTDE(IN)
!...This routine performs I/O.
      END FUNCTION  
      END INTERFACE 
      END MODULE 
