      MODULE ichop_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:48:25   2/14/04  
      INTEGER FUNCTION ichop (ISUBSH, ICSF) 
      INTEGER NNNW 
      PARAMETER(NNNW=214) 
      INTEGER, INTENT(IN) :: ISUBSH 
      INTEGER :: ICSF 
!VAST.../ORB5/ NKJ(IN)
!VAST...Calls: IQ
      END FUNCTION  
      END INTERFACE 
      END MODULE 
