      MODULE iq_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:48:38   2/14/04  
      INTEGER FUNCTION iq (ISUBSH, ICSF) 
      INTEGER, INTENT(IN) :: ISUBSH 
      INTEGER :: ICSF 
!VAST...Calls: IQA
      END FUNCTION  
      END INTERFACE 
      END MODULE 
