      MODULE lodcsh2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:49:02   2/14/04  
      SUBROUTINE lodcsh2(NFILE, NCORE, JB) 
      INTEGER NNNW 
      PARAMETER(NNNW=214) 
      INTEGER, INTENT(IN) :: NFILE 
      INTEGER, INTENT(OUT) :: NCORE 
      INTEGER , INTENT(IN) :: JB
!VAST.../DEF1/ NELEC(OUT)
!VAST.../ORB2/ NW(OUT)
!VAST.../ORB4/ NP(IN), NAK(IN)
!VAST.../ORB5/ NKJ(IN)
!VAST.../IOUNIT/ ISTDE(IN)
!VAST...Calls: PRSRSL, PRSRCN
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
