      MODULE lodplt_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:49:54   2/14/04  
      SUBROUTINE lodplt 
!VAST.../LIB92P/ LPLANT(OUT), NPLANT(OUT)
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
