      MODULE chkplt_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:49:50  12/27/06  
      SUBROUTINE chkplt 
!VAST.../LIB92P/ LPLANT(IN), NPLANT(INOUT)
!VAST...Calls: LODPLT, CONVRT
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
